# Generated by Django 4.1.4 on 2022-12-08 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="CLOSING_DATE",
        ),
        migrations.RemoveField(
            model_name="note",
            name="CREATION_DATE",
        ),
    ]
