# Generated by Django 4.1.2 on 2022-12-12 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_remove_note_closing_date_remove_note_creation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="state",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=500, verbose_name="state"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="note",
            name="description",
            field=models.CharField(max_length=14000, verbose_name="descripcion"),
        ),
    ]
