# Generated by Django 4.1.2 on 2022-12-12 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_note_state_alter_note_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="CREATION_DATE",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
