# Generated by Django 4.1.2 on 2022-12-12 21:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_note_creation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="CLOSING_DATE",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
